name: compile haxeflixel code test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Haxe
        uses: krdlab/setup-haxe@v1.5.1
        with: 
            haxe-version: 4.3.1

      - name: Install Haxelib Dependencies
        run: | 
          haxelib install flixel
          haxelib install lime
          haxelib install openfl
          haxelib run lime setup flixel
          haxelib install hxdiscord_rpc
          

      - name: Compile HaxeFlixel Project
        run: haxelib run lime build linux -debug
